
name: PR to Develop Analysis

on:
  pull_request:
    branches: [develop]

jobs:
  call-sonar:
    uses: microservices-final-project/ci-templates/.github/workflows/pr-to-develop.yaml@main
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}